# vmoptions: -Dspring.profiles.active=test
server.port: 9090

api:
  # Requests accept just this headers (optinal property). If property not exists, all headers are accepted
#  acceptedHeaders:
#    - "accept"
#    - "Content-Type"

  # When is not find in repository, then will try to do a request in this host
  host: "http://www.mocky.io"

  acceptedHeaders: "Accept,User-Agent,Content-Type"

  # Default headers to do a request
  defaultHeaders:
    -
      headerName: "Access-Control-Allow-Origin"
      headerValues:
        - "Connection"
        - "Keep-Alive"
    -
      headerName: "Content-Type"
      headerValues:
        - "application/json;charset=UTF-8"

  # Alternative hosts
  # When a request uri match with some pattern, than this host will be used
  uriConfigurations:
    -
      host: "http://some-site1.com"
      pattern: "/site1"
      prefixPath: "site1"
    -
      host: "http://some-site2.com"
      pattern: "/site2"
      prefixPath: "site2"

# Paths of json
file:
  # Look for this path to find json with a request
  base: "${FILE_BASE:mocks-test}"
  extension: ".json"
  # Save request (cache) in this path
  backup.path: "${FILE_BACKUP_PATH:backup-temp}"

# Initialize app in capture mode. All requests will be saved
captureState: true

# Optional, use if you want decode query parameters
decoder.characterEncoding: "UTF-8"

#debug: true
logging.level.ROOT: INFO
