# vmoptions: -Dspring.profiles.active=test

server.port: 9090

api:
  # Pay 7 precisa ser a raiz pq não dá pra adicionar um prefixo no marketplace
  host: "https://sandbox-api.pay7.com.br"

  acceptedHeaders: "Accept,User-Agent,Content-Type,X-Auth-User-Id,Authorization"

  defaultHeaders:
  -
    headerName: "Access-Control-Allow-Origin"
    headerValues:
    - "Connection"
    - "Keep-Alive"
  -
    headerName: "Content-Type"
    headerValues:
    - "application/json;charset=UTF-8"

  # Alternative hosts
  # When a request uri match with some pattern, than this host will be used
  uriConfigurations:
  -
    host: "http://tyrion-us-dev.kube.aws.elo7.io"
    pattern: "/tyrion"
    prefixPath: "tyrion"
  -
    host: "http://frenzy-br-integration-blue.aws.elo7.io/frenzy"
    pattern: "/frenzy"
    prefixPath: "frenzy"
  -
    host: "http://shipping7-api.kube.elo7aws.com.br"
    pattern: "/shipping7"
    prefixPath: "shipping7"
  -
    host: "https://sandbox-api.pay7.com.br"
    pattern: "/pay7"
    prefixPath: "" # pay7 está na raiz :/

# Paths of json
file:
  # Look for this path to find json with a request
  base: "${FILE_BASE:data}"
  extension: ".json"
  # Save request (cache) in this path
  backup.path: "${FILE_BACKUP_PATH:data-cache}"

# Initialize app in capture mode. All requests will be saved
captureState: true

decoder.characterEncoding: "UTF-8"

#debug: true
logging.level.ROOT: INFO
